---
name: List Repo

on:
  push:
    branches:
      - master

jobs:
  list-repo:
    runs-on: node:alpine
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: List Repo
      run: |
        cd path
        ls
    - name: List Repo
      run: ls
